custom:
  serverless-offline:
    httpPort: 5000

service: sls-jira
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-south-1

plugins:
  - serverless-plugin-typescript
  - serverless-offline


functions:
  - ${file(./functions/healthCheck.yml)}
  - ${file(./functions/task.yml)}
  - ${file(./functions/member.yml)}
