service: sls-jira
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

	
plugins:
  - serverless-plugin-typescript
  - serverless-offline


functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  getAllTasks:
    handler: task.getAllTasks
    events:
      - httpApi:
          path: /tasks
          method: get
